/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rnp_flite_FliteAPI */

#ifndef _Included_com_rnp_flite_FliteAPI
#define _Included_com_rnp_flite_FliteAPI

/*
 * Class:     com_rnp_flite_FliteAPI
 * Method:    inisialisasi
 * Signature: (IIDDDIDZDD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rnp_flite_FliteAPI_inisialisasi
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jdouble, jint, jdouble, jboolean, jdouble, jdouble);

/*
 * Class:     com_rnp_flite_FliteAPI
 * Method:    start
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rnp_flite_FliteAPI_start
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_rnp_flite_FliteAPI
 * Method:    getSound
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rnp_flite_FliteAPI_getSound
  (JNIEnv *, jobject, jstring, jstring);

#endif
